### ISSUE TITLE
Login with Patreon logic

### ISSUE THREAD

**Issue by bigt11** [Patreon/patreon-wordpress#1]
First time commenter, so go easy.  Im trying to integrate Patreon with my wordpress site.  I was able to get the oAuth working by creating credentials in Patreon and adding them to the WP settings.  I am able to click the login with patreon button and authorize my WP site to share credentials.  I know your readme file states user creation scenarios.

Using 
WP 4.4.1
Buddypress 2.4.3
bbPress 2.5.8
Github Patreon commit 1fe961a 
1.  User does not exist in WP, I login with Patreon, it makes a new user and logs them in (fine).  I then logout the user, then try and login to the WP site again using the login with patreon button, it takes me to patreon again and I authorize the connection again to my site, then in the login area, it says.  "You can now login with your wordpress username/password."  Which username and pass is it referring to? I know the username is the persons name that they used on patreon.  So what password would they use?  When the user gets created, it uses a random password when creating there WP account and does not email the user there username or pass.  Attached is a modified patreon_login.php which will notify user of there username and allow them to change there password.   
2.  When I try and login with patreon, the 2nd time or more, Is it supposed to actually log me in, because it currently does not, and just update that users patreon meta info?  Seems stuck at this point.  Always says  "You can now login with your wordpress username/password."  
3.  Is the intent of the login with patron button for them to always use this button, or just use it once, and then the user would forever use the new WP login and pass after the initial login with patron process? 
4. Im sure I will be contacting you guys more, so is this where you want me to submit my questions and requests?

[patreon_login.zip](https://github.com/Patreon/patreon-wordpress/files/91391/patreon_login.zip)

**Comment by bigt11** [comment]
I think i answered my own #2.  It looks like in patreon_login.php in the else was commented out lines to log the user in.  I also just redirected to the home_url().

**Comment by goodux** [comment]
Hi BigT, 

I modified that functionality slightly due to a possible security threat but commented out the old implementation. Basically its a bad idea to have Wordpress auto login after connecting with Wordpress.

Wordpress also doesn't send passwords over email, so the user will need to follow the reset password flow. This is also a security consideration.

Basically the idea is for the Patreon user to connect once, then utilise their Wordpress accounts.

**Comment by bigt11** [comment]
OK how about this.  the user initially uses the connect with patreon, it creates them an account.  Then redirects to the reset your password page automatically, so then and there they can reset the random generated password.  This page will also tell them there username.  The line of code I sent, will notify them via email of the username that was created and offer a password reset link as well, dont know if that would be redundant though.  After the user resets the password, they will be redirected to the login page.  It seems that this reset password page might have to be custom compared the the built in WP reset password page to allow for the constant redirects and the ability to show username?

**Comment by bigt11** [comment]
Since the ultimate goal is to have the user become a WP user, the update the users meta with Patreon info, the act of updating the user meta would trigger when attempting to view patreon content?  

Would the only way to know a user is Patreon oriented (originated) is to do a quick user meta check to see if anything is in the patreon user meta without having to ping patreons servers?  The only difference it seems between a naturally signed up new user compared to a Patreon user is that extra meta data?

So lets say they now do the steps im my above comments.  When they login, the login with patreon button will still show, they will have a harder time knowing not to hit the login with patreon button again because they have an account now, and it will not log them in.  Should a error message come up directing them that they have already created an account and to use there username and pass to login, and offer a link to the login page.  Obviously if they re-use the login with patreon button again, it should update there user meta again.

**Comment by bigt11** [comment]
I know in your notes that it mentions A connect this account with patreon.  Do you think maybe that the user should just create an account naturally, then connect it with patreon, if having them login with patreon then reset password and all that eventually gets too complicated?

**Comment by codebard** [comment]
Outdated old issue. Closing.
