### ISSUE TITLE
Setting patreon levels with REST API doesn't work

### ISSUE THREAD

**Issue by TamedTornado** [Patreon/patreon-wordpress#100]
I've tried this a bit, and it seems like setting the patreon-level and patreon-total-patronage-level metadata doesn't seem to work via REST. A look at the source shows me no calls to register_meta.

Is this a deliberate design decision? I could really use this functionality.

**Comment by codebard** [comment]
This can be just handled by using the code you have provided in any custom plugin or theme code. The code you provided would directly fix this issue, as mentioned in the relevant PR.

https://github.com/Patreon/patreon-wordpress/pull/101#issuecomment-650435580
