### ISSUE TITLE
Missing php files

### ISSUE THREAD

**Issue by nboliver** [Patreon/patreon-wordpress#15]
The current version of the plugin is missing admin PHP files, causing the site to break when the plugin is activated. Rolling back the latest commit seems to partially fix the problems.

**Comment by madmonkey85** [comment]
Also experiencing major issues when activating plugin, same issue as above.

**Comment by servingworlds** [comment]
Also experiencing pain implementing due to missing plugins. Great work so far though, very exciting implementation. 
Timeframe to rectify missing files as below?

include 'admin/patreon-options-page.php';
include 'admin/patreon-content-metabox.php';

**Comment by spencerhandley** [comment]
Hey Folks, 
This plugin is currently still in the works. We are hoping to relaunch it to creators soon. Sorry about the confusion. 

If you put your email in this form, we will update you when we are ready to release it https://patreonforms.typeform.com/to/S4eMQT

**Comment by codebard** [comment]
Outdated old issue. Closing.
