### ISSUE TITLE
Redirect URL results in a 500 error

### ISSUE THREAD

**Issue by azanebrain** [Patreon/patreon-wordpress#16]
I almost have this plugin up and running, but I'm hitting an error after the user allows Patreon to log into the site. The redirect URL is hit with the `code` and `state` parameters, but my server is responding with 500: 

```
 http://mysite.com/patreon-authorization/?code=<some code>&state=<some state>  500 (Internal Server Error)
```

If I copy and paste the requested URL in a new tab, I'm able to hit my site and I get redirected to the homepage, so I'm not sure why the automated redirect is failing.

I've tried adding a 'patreon-authorization' page, but I'm still hitting this error. The only other possibility I can think of is going from Patreon's HTTPS to my site's non-SSL, but that seems like it shouldn't be a problem.

Thanks for the help!

**Comment by telaviv** [comment]
Hey again @azanebrain! 

We are totally aware of the issue and a big change is coming. After the new version is released, please let us know if you still run into this we expect it should be resolved.
