### ISSUE TITLE
protectContentFromUser feature request

### ISSUE THREAD

**Issue by bigt11** [Patreon/patreon-wordpress#2]
looks like the function protectContentFromUser in patreon_frontend.php checks to see what patron level they are compared to the entered level in the post.  If patron is less than said number, it will display the PatreonCampaignBanner().  Maybe it should just redirect to a page or post of Admins choosing in the Patreon settings.  This way there is 1 master page explaining your sites "Patreon Pitch" and how they can sign up.  Admin can design and put any info they want express on the page.

**Comment by goodux** [comment]
I like this. I will develop this functionality for you.

**Comment by bigt11** [comment]
Well, who doesn't want both.  Since you are currently changing the $content anyways, you could just fetch the post ID of the post that will be the pitch page from the Patreon settings, and show it instead as the $content.  Also since the pitch page is standalone obviously that would be the page to sell the idea of patreon on without them having to attempt to view a patreon protected item..

**Comment by codebard** [comment]
This is now handled with unified pledge flow on Patreon side. Closing.
