### ISSUE TITLE
Imitate logged-in patron for local testing

### ISSUE THREAD

**Issue by skazhikadyadya** [Patreon/patreon-wordpress#24]
Hi! I try to modify our theme for display content of posts only for patrons included Posts name and another. I try to do it on local dev server. Can I set any variables like a patron logged-in, it needed for design tests? 

Thank you.

**Comment by nperickson** [comment]
Hey @skazhikadyadya - You may want to post this over on https://www.patreondevelopers.com/c/patreon-wordpress-plugin-support which is where our Wordpress dev team troubleshoots and assists with these types of issues.

**Comment by codebard** [comment]
Outdated old issue. Closing.
