### ISSUE TITLE
Sandbox accounts

### ISSUE THREAD

**Issue by bigt11** [Patreon/patreon-wordpress#3]
How are you able to test an active campaign?  Is there a way to have a fake campaign with patrons to test the implementation of the code.  I cant fully test any changes to my site without an active campaign and patrons, but can't launch campaign without testing.  Chicken and the Egg

**Comment by 21echoes** [comment]
we'll be looking into sandbox accounts sometime within the coming year, but they won't be coming any time soon. for now, we encourage you to launch your campaign before publicizing it, and test while it's launched but no one knows about it yet.
