### ISSUE TITLE
Reset API Key Credentials in "Patreon Settings"

### ISSUE THREAD

**Issue by zeyka** [Patreon/patreon-wordpress#6]
When the API key credentials are set in menu _Patreon Settings_ for the first time, fields disappear.  Now if you want to change credentials is not possible even reinstalling the plugin. There should be a possibility to reset the credentials.

**Comment by 21echoes** [comment]
Hey @zeyka ! I'm unable to reproduce this issue. Could you re-open this issue with reproduction steps or screenshots if it's still happening for you?
