### ISSUE TITLE
How to connect with patron account

### ISSUE THREAD

**Issue by localjo** [Patreon/patreon-wordpress#82]
I want to add features to my own WordPress plugin that are only unlocked for my patrons. I thought this could be done by having the patrons install `patreon-wordpress` on their site, alongside my plugin, and logging in with their patron account. Then [I thought I could use the `getUserPatronage` function](https://paper.dropbox.com/doc/Patreon-WordPress-how-to-lock-any-part-of-your-Website--AbIfW2McceTuN5ZMcBIYogxiAg-dqneEVjvuYrPbkEJfOuhG) to check if they should have access to the features.

But after trying to configure this, I realized that the `patreon-wordpress` plugin seems to be designed only for restricting access to content on creator's sites, and that there doesn't seem to be a way for patrons to use the plugin in a standalone fashion.

Is my understanding correct? And is there a recommended way to restrict my own plugin features to patrons?

https://github.com/localjo/quotable-wp/issues/3

**Comment by codebard** [comment]
Yes, you can definitely use the plugin to make use of its already made features. 

For example Patron Pro is such a plugin which is installed alongside PW as an addon and extends PW's functionalities.

https://codebard.com/patron-plugin-pro

You can do the same - you can bundle your plugin with PW, or have users install PW separately and also install your plugin. And then use getUserPatronage or other functions to do whatever you need. There are numerous hooks and filters in PW as well.

Content locking features, Patreon login features - all of them should work out of the box, and you should be able to hook into almost all of them to help integrate with your plugin.

**Comment by localjo** [comment]
Sorry, I think I miscommunicated my question. I want to know if there is a way to restrict features in my own wordpress plugin that is installed on patron's sites (not on creator's sites). The users of my plugin are not creators, and will not have client secrets or API keys.

Essentially, I want users to be able to install my WordPress plugin, click a "Connect with Patreon" button, log in with their *patron* Patreon account (again, they are not creators), and then get access to patron-only features that I include in my plugin.

My plugin would be installed on a *patron* site, not on a *creator* site.

Is there a way to implement this? The `patreon-wordpress` plugin seems to be for creators only, and seems to require users to have a creator account where they create a client and get secret keys.

**Comment by codebard** [comment]
Now your requirement is clear.

Currently there isnt any way to be able to do this. The patrons would need to have clients created for their sites. 

A workaround could be your plugin contacting your site to get information, where your site has PW and whatever needed code which would interpret your patrons' access rights. If patrons are saved as attached to certain sites, you can easily modify behavior of your plugin in remote site. You can create keys for remote sites in your own and then run your own service etc.
