### ISSUE TITLE
Patreon_Frontend::make_creator_name_for_interface() is breaking

### ISSUE THREAD

**Issue by Oshova** [Patreon/patreon-wordpress#94]
> Warning: Missing argument 1 for Patreon_Frontend::make_creator_name_for_interface(), called in /home/site/public_html/blog/wp-content/plugins/patreon-connect/classes/patreon_frontend.php on line 194 and defined in /home/site/public_html/blog/wp-content/plugins/patreon-connect/classes/patreon_frontend.php on line 1248
> 
> Warning: Missing argument 2 for Patreon_Frontend::make_creator_name_for_interface(), called in /home/site/public_html/blog/wp-content/plugins/patreon-connect/classes/patreon_frontend.php on line 194 and defined in /home/site/public_html/blog/wp-content/plugins/patreon-connect/classes/patreon_frontend.php on line 1248
> 
> Warning: Missing argument 3 for Patreon_Frontend::make_creator_name_for_interface(), called in /home/site/public_html/blog/wp-content/plugins/patreon-connect/classes/patreon_frontend.php on line 194 and defined in /home/site/public_html/blog/wp-content/plugins/patreon-connect/classes/patreon_frontend.php on line 1248
> 
> Warning: Missing argument 4 for Patreon_Frontend::make_creator_name_for_interface(), called in /home/site/public_html/blog/wp-content/plugins/patreon-connect/classes/patreon_frontend.php on line 194 and defined in /home/site/public_html/blog/wp-content/plugins/patreon-connect/classes/patreon_frontend.php on line 1248
> 
> Warning: Missing argument 5 for Patreon_Frontend::make_creator_name_for_interface(), called in /home/site/public_html/blog/wp-content/plugins/patreon-connect/classes/patreon_frontend.php on line 194 and defined in /home/site/public_html/blog/wp-content/plugins/patreon-connect/classes/patreon_frontend.php on line 1248

The make_creator_name_for_interface function is expecting 5 arguments, and when it doesn't get them it creates 5 errors. These errors are only appearing since this function was added, and the plugin was updated.

There needs to be a better way of handling these errors. You've got good fallbacks within the function to deal with a creator not wanting to show their full name etc, but it appears that this function can easily be called without a user linking their Patreon to the site, and that causes these errors.

**Comment by codebard** [comment]
Aside from warnings should not be set to on in production sites, make_creator_name_for_interface is called only inside the functions which make the labels over and under the gated post interface. Users should not be able to gate any post before successfully linking their site to Patreon and the plugin being able to acquire their creator id from Patreon.

At which page have you encountered these warnings?

**Comment by Oshova** [comment]
> Aside from warnings should not be set to on in production sites

Yes, that wasn't my decision... I will be having words.

> At which page have you encountered these warnings?

This is happening on the page to link to Patreon.

In this instance the section currently goes:
- These errors
- "To view this content, you must be a member of the Patreon etc etc"
- Button to unlock with Patreon

I'll check back through to see if I'm doing anything that might call this function in there. But I don't think I've changed anything other than updating the plugin. It's just that my initial thought looking through the plugin was that there should be a way to handle this error where the function is called on line 194. 

Well I'll have a look through again to see what is causing the issue on my end.

**Comment by codebard** [comment]
Can you PM me the link to a page where this is happening? You can PM it to Codebard user at the official support forum below:

https://www.patreondevelopers.com/c/patreon-wordpress-plugin-support

If your site is properly linked, this should not be happening. That function getting called with empty params is just weird.

**Comment by codebard** [comment]
Please retry downloading this master, setting it up and check out if this fixes your issue.
