### ISSUE TITLE
This repository has not been updated in months

### ISSUE THREAD

**Issue by rparrett** [Patreon/patreon-wordpress#96]
Several new versions of the plugin have been released, but this repo hasn't been updated.

Is development no longer taking place on github?

**Comment by rparrett** [comment]
I see that new branches are now being created for each new release while the master branch remains stale.

I suppose there's some sort of slightly unusual development flow happening here that I don't understand.

I'll go ahead and close this.

**Comment by codebard** [comment]
Currently the master is updated from the releases in a schedule longer than the releases. Then tagged releases are PR'ed into master in longer intervals.

At this moment, the releases at WP repo (which follows the tagged releases here) are what you can watch for tracking the progress.

Or, the tagged releases here.

**Comment by codebard** [comment]
Additionally, for development purposes it would be much better to just use the plugin published at WP repo, and develop on it by using its action hooks and filters (and functions) than to fork this repo and modify it. The existing hooks and filters already allow modification of almost all plugin behavior. Majority of its functions can be used outside the plugin, many without even needing to initialize the plugin itself. These should provide you great flexibility in developing your modifications and ensure their longevity.

**Comment by rparrett** [comment]
We wish we didn't have to maintain a fork. The main things preventing us from using official releases are:

- we need caching
- we need the user's email address even if it is unverified
- we need wordpress users to be created with friendlier usernames
- we have also customized some error messages that our users seem to be confused by

Some of these needs things are unique to our setup (11k+ patrons, many more existing users via memberpress, and an additional third party connection with discourse)

But we do make use of hooks/filters to when we can, and appreciate them.

**Comment by codebard** [comment]
I very much feel that these should be doable using existing hooks and functions. If you get in touch with me via ozgur@c.patreon.com, we can sync and come up with a solution that will make it easier for you to use the integration.
