### ISSUE TITLE
Use of undefined constant PATREON_TEXT_YOU_HAVE_NO_REWARDS_IN_THIS_CAMPAIGN

### ISSUE THREAD

**Issue by SleepProgger** [Patreon/patreon-wordpress#97]
Using this plugin i get the following warning when accessing patreon content:
```
PHP Warning:  Use of undefined constant PATREON_TEXT_YOU_HAVE_NO_REWARDS_IN_THIS_CAMPAIGN - assumed 'PATREON_TEXT_YOU_HAVE_NO_REWARDS_IN_THIS_CAMPAIGN' (this will
throw an Error in a future version of PHP) in /htdocs/wp-content/plugins/patreon-connect/classes/patreon_wordpress.php on line 1573
```

This is the only occurrence of `PATREON_TEXT_YOU_HAVE_NO_REWARDS_IN_THIS_CAMPAIGN` in the whole plugin, so is there a typo or should this be in deed a string ?

**Comment by codebard** [comment]
This should have gone away by 1.4.6. You can just update.

**Comment by codebard** [comment]
Closing.
